### PR TITLE
deps: bump make-fetch-happen

### PR DESCRIPTION
**Pull request by claudiomedina**
Fix https://www.npmjs.com/advisories/1184

### CODE REVIEW

**Comment by yovanoc** [comment]
It would be good to upgrade to a better major version because of this https://github.com/npm/make-fetch-happen/issues/17

**Comment by yovanoc** [comment]
@claudiomedina Could you put version 8.0.2 instead for the fix?

**Comment by yovanoc** [comment]
Please @evocateur we can pay a little for upgrading this, it's really blocking. thanks!

**Comment by claudiomedina** [comment]
> @claudiomedina Could you put version 8.0.2 instead for the fix?

@yovanoc Is it safe to bump that much?

**Comment by yovanoc** [comment]
For what i've check yes but maybe I missed something...

**Comment by evocateur** [comment]
Literally all you need to do is reset your lockfile. If you got here via a Lerna transitive dependency (likely), you can target it a bit narrower by removing then re-adding `lerna`:

```sh
npm rm -D lerna
npm i -D lerna
```

This is a fork of `pacote` that I only made due to lack of upstream maintenance at the time. As that issue has been resolved, I will no longer be maintaining this fork once I can carve out the time to move Lerna off of it.

**Comment by yovanoc** [comment]
I still have this issue. But the problem only happen when you're creating a got instance in a single package and import it in another.

**Pull request closed without merging**
